'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DSD.MotionLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALMStopMode.
        '''</summary>
        Friend ReadOnly Property ALM制动方式() As String
            Get
                Return ResourceManager.GetString("ALM制动方式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALMValidSignal.
        '''</summary>
        Friend ReadOnly Property ALM有效电平() As String
            Get
                Return ResourceManager.GetString("ALM有效电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d_zipdrive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d_zipdrive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetEL.
        '''</summary>
        Friend ReadOnly Property EL设置() As String
            Get
                Return ResourceManager.GetString("EL设置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMGSignalEnable.
        '''</summary>
        Friend ReadOnly Property EMG信号使能() As String
            Get
                Return ResourceManager.GetString("EMG信号使能", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMGValidSignal.
        '''</summary>
        Friend ReadOnly Property EMG有效电平() As String
            Get
                Return ResourceManager.GetString("EMG有效电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERCSignal.
        '''</summary>
        Friend ReadOnly Property ERC信号() As String
            Get
                Return ResourceManager.GetString("ERC信号", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERCSignalEnable.
        '''</summary>
        Friend ReadOnly Property ERC信号使能() As String
            Get
                Return ResourceManager.GetString("ERC信号使能", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERCShutTime.
        '''</summary>
        Friend ReadOnly Property ERC关断时间() As String
            Get
                Return ResourceManager.GetString("ERC关断时间", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERCValidWidth.
        '''</summary>
        Friend ReadOnly Property ERC有效宽度() As String
            Get
                Return ResourceManager.GetString("ERC有效宽度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERCValidSignal.
        '''</summary>
        Friend ReadOnly Property ERC有效电平() As String
            Get
                Return ResourceManager.GetString("ERC有效电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INPSignalEnable.
        '''</summary>
        Friend ReadOnly Property INP信号使能() As String
            Get
                Return ResourceManager.GetString("INP信号使能", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INPValidSignal.
        '''</summary>
        Friend ReadOnly Property INP有效电平() As String
            Get
                Return ResourceManager.GetString("INP有效电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Language() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Language", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maintenance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maintenance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请检查是否给控件赋值正确.
        '''</summary>
        Friend ReadOnly Property M请检查是否给控件赋值正确() As String
            Get
                Return ResourceManager.GetString("M请检查是否给控件赋值正确", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PCSAllowOrForbid.
        '''</summary>
        Friend ReadOnly Property PCS允许或禁止() As String
            Get
                Return ResourceManager.GetString("PCS允许或禁止", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PCSValidSignal.
        '''</summary>
        Friend ReadOnly Property PCS有效电平() As String
            Get
                Return ResourceManager.GetString("PCS有效电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Power() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Power", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reset_mc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset mc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SDAllowOrForbid.
        '''</summary>
        Friend ReadOnly Property SD允许或禁止() As String
            Get
                Return ResourceManager.GetString("SD允许或禁止", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SDWorkMode.
        '''</summary>
        Friend ReadOnly Property SD工作模式() As String
            Get
                Return ResourceManager.GetString("SD工作模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SDValidSignal.
        '''</summary>
        Friend ReadOnly Property SD有效电平() As String
            Get
                Return ResourceManager.GetString("SD有效电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SEVONSignal.
        '''</summary>
        Friend ReadOnly Property SEVON电平() As String
            Get
                Return ResourceManager.GetString("SEVON电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StopMode.
        '''</summary>
        Friend ReadOnly Property Stop模式() As String
            Get
                Return ResourceManager.GetString("Stop模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SMode.
        '''</summary>
        Friend ReadOnly Property S型() As String
            Get
                Return ResourceManager.GetString("S型", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TMode.
        '''</summary>
        Friend ReadOnly Property T型() As String
            Get
                Return ResourceManager.GetString("T型", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上下电信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX上下电信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX上下电信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 与已经有的IO点有冲突.
        '''</summary>
        Friend ReadOnly Property XX与已经有的IO点有冲突() As String
            Get
                Return ResourceManager.GetString("XX与已经有的IO点有冲突", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 保存IO设置错误；请核对路径-&quot;.
        '''</summary>
        Friend ReadOnly Property XX保存IO设置错误_请核对路径() As String
            Get
                Return ResourceManager.GetString("XX保存IO设置错误_请核对路径", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 关闭连续直线运动信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX关闭连续直线运动信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX关闭连续直线运动信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写.
        '''</summary>
        Friend ReadOnly Property XX写() As String
            Get
                Return ResourceManager.GetString("XX写", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入输出点电平信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX写入输出点电平信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX写入输出点电平信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写文件配置错误.
        '''</summary>
        Friend ReadOnly Property XX写文件配置错误() As String
            Get
                Return ResourceManager.GetString("XX写文件配置错误", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 卡类型文件不存在.
        '''</summary>
        Friend ReadOnly Property XX卡类型文件不存在() As String
            Get
                Return ResourceManager.GetString("XX卡类型文件不存在", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 号卡第.
        '''</summary>
        Friend ReadOnly Property XX号卡第() As String
            Get
                Return ResourceManager.GetString("XX号卡第", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 启动手轮运动函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX启动手轮运动函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX启动手轮运动函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 启动连续直线插补错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX启动连续直线插补错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX启动连续直线插补错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 启动连续直线运动信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX启动连续直线运动信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX启动连续直线运动信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 复位超时，检查复位速度是否过低！.
        '''</summary>
        Friend ReadOnly Property XX复位超时_检查复位速度是否过低() As String
            Get
                Return ResourceManager.GetString("XX复位超时_检查复位速度是否过低", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 实例化轴类失败；请退出程序，重新进入.
        '''</summary>
        Friend ReadOnly Property XX实例化轴类失败_请退出程序_重新进入() As String
            Get
                Return ResourceManager.GetString("XX实例化轴类失败_请退出程序_重新进入", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 已经配置完成.
        '''</summary>
        Friend ReadOnly Property XX已经配置完成() As String
            Get
                Return ResourceManager.GetString("XX已经配置完成", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 打开连续直线插补！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX打开连续直线插补_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX打开连续直线插补_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行CSTP停止轴函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行CSTP停止轴函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行CSTP停止轴函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行ST段时间分配函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行ST段时间分配函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行ST段时间分配函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行ST运动函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行ST运动函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行ST运动函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行S型运动曲线函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行S型运动曲线函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行S型运动曲线函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行S段时间分配函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行S段时间分配函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行S段时间分配函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行S运动函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行S运动函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行S运动函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行S连续运动函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行S连续运动函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行S连续运动函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行T型运动曲线函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行T型运动曲线函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行T型运动曲线函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行T连续运动函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行T连续运动函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行T连续运动函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行减速停止轴函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行减速停止轴函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行减速停止轴函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行单独直线插补错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行单独直线插补错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行单独直线插补错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行复位函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行复位函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行复位函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行改变速度函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行改变速度函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行改变速度函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行紧急停止所有轴函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行紧急停止所有轴函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行紧急停止所有轴函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 执行紧急停止轴函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX执行紧急停止轴函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX执行紧急停止轴函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 找不到.
        '''</summary>
        Friend ReadOnly Property XX找不到() As String
            Get
                Return ResourceManager.GetString("XX找不到", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改变目标位置函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX改变目标位置函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX改变目标位置函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改变目标位置失败!.
        '''</summary>
        Friend ReadOnly Property XX改变目标位置失败() As String
            Get
                Return ResourceManager.GetString("XX改变目标位置失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 是否有对应的IO点.
        '''</summary>
        Friend ReadOnly Property XX是否有对应的IO点() As String
            Get
                Return ResourceManager.GetString("XX是否有对应的IO点", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更新保存轴关系表错误；请重新配置.
        '''</summary>
        Friend ReadOnly Property XX更新保存轴关系表错误_请重新配置() As String
            Get
                Return ResourceManager.GetString("XX更新保存轴关系表错误_请重新配置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更新‘轴号’表格错误.
        '''</summary>
        Friend ReadOnly Property XX更新轴号表格错误() As String
            Get
                Return ResourceManager.GetString("XX更新轴号表格错误", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更新‘轴名称’表格错误.
        '''</summary>
        Friend ReadOnly Property XX更新轴名称表格错误() As String
            Get
                Return ResourceManager.GetString("XX更新轴名称表格错误", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更新‘轴对应关系’表格错误.
        '''</summary>
        Friend ReadOnly Property XX更新轴对应关系表格错误() As String
            Get
                Return ResourceManager.GetString("XX更新轴对应关系表格错误", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未发现该轴参数文件.
        '''</summary>
        Friend ReadOnly Property XX未发现该轴参数文件() As String
            Get
                Return ResourceManager.GetString("XX未发现该轴参数文件", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 板卡初始化失败.
        '''</summary>
        Friend ReadOnly Property XX板卡初始化失败() As String
            Get
                Return ResourceManager.GetString("XX板卡初始化失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 板卡初始化失败,轴电平参数不存在！.
        '''</summary>
        Friend ReadOnly Property XX板卡初始化失败_轴电平参数不存在() As String
            Get
                Return ResourceManager.GetString("XX板卡初始化失败_轴电平参数不存在", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要保存的数据.
        '''</summary>
        Friend ReadOnly Property XX没有要保存的数据() As String
            Get
                Return ResourceManager.GetString("XX没有要保存的数据", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要保存的数据，请检查数据.
        '''</summary>
        Friend ReadOnly Property XX没有要保存的数据_请检查数据() As String
            Get
                Return ResourceManager.GetString("XX没有要保存的数据_请检查数据", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要删除的数据.
        '''</summary>
        Friend ReadOnly Property XX没有要删除的数据() As String
            Get
                Return ResourceManager.GetString("XX没有要删除的数据", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要删除的轴.
        '''</summary>
        Friend ReadOnly Property XX没有要删除的轴() As String
            Get
                Return ResourceManager.GetString("XX没有要删除的轴", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要删除的配置.
        '''</summary>
        Friend ReadOnly Property XX没有要删除的配置() As String
            Get
                Return ResourceManager.GetString("XX没有要删除的配置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要读取的文件!.
        '''</summary>
        Friend ReadOnly Property XX没有要读取的文件() As String
            Get
                Return ResourceManager.GetString("XX没有要读取的文件", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要配置的点.
        '''</summary>
        Friend ReadOnly Property XX没有要配置的点() As String
            Get
                Return ResourceManager.GetString("XX没有要配置的点", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要配置的轴.
        '''</summary>
        Friend ReadOnly Property XX没有要配置的轴() As String
            Get
                Return ResourceManager.GetString("XX没有要配置的轴", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有要配置的轴号.
        '''</summary>
        Friend ReadOnly Property XX没有要配置的轴号() As String
            Get
                Return ResourceManager.GetString("XX没有要配置的轴号", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 没有配置IO点.
        '''</summary>
        Friend ReadOnly Property XX没有配置IO点() As String
            Get
                Return ResourceManager.GetString("XX没有配置IO点", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 添加高速比较位置点错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX添加高速比较位置点错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX添加高速比较位置点错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 添加高速比较点失败！.
        '''</summary>
        Friend ReadOnly Property XX添加高速比较点失败() As String
            Get
                Return ResourceManager.GetString("XX添加高速比较点失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 添加高速比较点错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX添加高速比较点错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX添加高速比较点错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 清除比较点失败！.
        '''</summary>
        Friend ReadOnly Property XX清除比较点失败() As String
            Get
                Return ResourceManager.GetString("XX清除比较点失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 清除高速比较点错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX清除高速比较点错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX清除高速比较点错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 清除高速比较通道比较点错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX清除高速比较通道比较点错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX清除高速比较通道比较点错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 获取比较器状态失败！.
        '''</summary>
        Friend ReadOnly Property XX获取比较器状态失败() As String
            Get
                Return ResourceManager.GetString("XX获取比较器状态失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 获取高速比较位置当前状态错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX获取高速比较位置当前状态错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX获取高速比较位置当前状态错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 获取高速比较通道比较模式错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX获取高速比较通道比较模式错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX获取高速比较通道比较模式错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 获取高速比较通道脉冲宽度错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX获取高速比较通道脉冲宽度错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX获取高速比较通道脉冲宽度错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置CMP比较值失败!.
        '''</summary>
        Friend ReadOnly Property XX设置CMP比较值失败() As String
            Get
                Return ResourceManager.GetString("XX设置CMP比较值失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置EZ信号函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置EZ信号函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置EZ信号函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置S运动速度函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置S运动速度函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置S运动速度函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置T运动速度函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置T运动速度函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置T运动速度函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置到位信息信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置到位信息信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置到位信息信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置单独直线插补速度错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置单独直线插补速度错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置单独直线插补速度错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置复位EZ信号信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置复位EZ信号信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置复位EZ信号信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置复位逻辑电平信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置复位逻辑电平信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置复位逻辑电平信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置手轮脉冲计数方式函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置手轮脉冲计数方式函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置手轮脉冲计数方式函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置报警信号电平信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置报警信号电平信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置报警信号电平信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置比较器触发条件失败!.
        '''</summary>
        Friend ReadOnly Property XX设置比较器触发条件失败() As String
            Get
                Return ResourceManager.GetString("XX设置比较器触发条件失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置比较输出电平失败!.
        '''</summary>
        Friend ReadOnly Property XX设置比较输出电平失败() As String
            Get
                Return ResourceManager.GetString("XX设置比较输出电平失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置直线插补脉冲当量信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置直线插补脉冲当量信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置直线插补脉冲当量信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置编码器位置函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置编码器位置函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置编码器位置函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置编码器函数函数错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置编码器函数函数错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置编码器函数函数错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置编码器计数模式信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置编码器计数模式信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置编码器计数模式信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置脉冲发生模式信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置脉冲发生模式信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置脉冲发生模式信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置螺旋插补直线信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置螺旋插补直线信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置螺旋插补直线信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置轴脉冲信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置轴脉冲信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置轴脉冲信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置连续直线S段匀速时间信息错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置连续直线S段匀速时间信息错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置连续直线S段匀速时间信息错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置连续直线插补速度错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置连续直线插补速度错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置连续直线插补速度错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置高速比较位置比较模式错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置高速比较位置比较模式错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置高速比较位置比较模式错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置高速比较位置脉冲宽度错误！错误信息为：.
        '''</summary>
        Friend ReadOnly Property XX设置高速比较位置脉冲宽度错误_错误信息为() As String
            Get
                Return ResourceManager.GetString("XX设置高速比较位置脉冲宽度错误_错误信息为", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ,请重新上电复位！.
        '''</summary>
        Friend ReadOnly Property XX请重新上电复位() As String
            Get
                Return ResourceManager.GetString("XX请重新上电复位", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 读取.
        '''</summary>
        Friend ReadOnly Property XX读取() As String
            Get
                Return ResourceManager.GetString("XX读取", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 轴！.
        '''</summary>
        Friend ReadOnly Property XX轴() As String
            Get
                Return ResourceManager.GetString("XX轴", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 轴配置！.
        '''</summary>
        Friend ReadOnly Property XX轴配置() As String
            Get
                Return ResourceManager.GetString("XX轴配置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 输入点IO未配置!.
        '''</summary>
        Friend ReadOnly Property XX输入点IO未配置() As String
            Get
                Return ResourceManager.GetString("XX输入点IO未配置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 输入点IO状态格式错误!.
        '''</summary>
        Friend ReadOnly Property XX输入点IO状态格式错误() As String
            Get
                Return ResourceManager.GetString("XX输入点IO状态格式错误", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 输入点状态异常！.
        '''</summary>
        Friend ReadOnly Property XX输入点状态异常() As String
            Get
                Return ResourceManager.GetString("XX输入点状态异常", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 输出点：.
        '''</summary>
        Friend ReadOnly Property XX输出点() As String
            Get
                Return ResourceManager.GetString("XX输出点", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 输出点IO未配置!.
        '''</summary>
        Friend ReadOnly Property XX输出点IO未配置() As String
            Get
                Return ResourceManager.GetString("XX输出点IO未配置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 输出点IO状态格式错误!.
        '''</summary>
        Friend ReadOnly Property XX输出点IO状态格式错误() As String
            Get
                Return ResourceManager.GetString("XX输出点IO状态格式错误", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 输出点状态异常！.
        '''</summary>
        Friend ReadOnly Property XX输出点状态异常() As String
            Get
                Return ResourceManager.GetString("XX输出点状态异常", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 速度发送失败！.
        '''</summary>
        Friend ReadOnly Property XX速度发送失败() As String
            Get
                Return ResourceManager.GetString("XX速度发送失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 高速比较位设置失败！.
        '''</summary>
        Friend ReadOnly Property XX高速比较位设置失败() As String
            Get
                Return ResourceManager.GetString("XX高速比较位设置失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to POW.
        '''</summary>
        Friend ReadOnly Property 上电() As String
            Get
                Return ResourceManager.GetString("上电", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 不存在此轴参数.
        '''</summary>
        Friend ReadOnly Property 不存在此轴参数() As String
            Get
                Return ResourceManager.GetString("不存在此轴参数", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 不理.
        '''</summary>
        Friend ReadOnly Property 不理() As String
            Get
                Return ResourceManager.GetString("不理", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RunScale.
        '''</summary>
        Friend ReadOnly Property 传动比() As String
            Get
                Return ResourceManager.GetString("传动比", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SEVONRAYSignal.
        '''</summary>
        Friend ReadOnly Property 伺服RAY电平() As String
            Get
                Return ResourceManager.GetString("伺服RAY电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 伺服报警.
        '''</summary>
        Friend ReadOnly Property 伺服报警() As String
            Get
                Return ResourceManager.GetString("伺服报警", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Position.
        '''</summary>
        Friend ReadOnly Property 位置() As String
            Get
                Return ResourceManager.GetString("位置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EditedPosition.
        '''</summary>
        Friend ReadOnly Property 位置编辑() As String
            Get
                Return ResourceManager.GetString("位置编辑", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LowSignal.
        '''</summary>
        Friend ReadOnly Property 低电平() As String
            Get
                Return ResourceManager.GetString("低电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LowSpeed.
        '''</summary>
        Friend ReadOnly Property 低速() As String
            Get
                Return ResourceManager.GetString("低速", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UseIOPoint.
        '''</summary>
        Friend ReadOnly Property 使用IO点() As String
            Get
                Return ResourceManager.GetString("使用IO点", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SAVE.
        '''</summary>
        Friend ReadOnly Property 保存() As String
            Get
                Return ResourceManager.GetString("保存", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SaveParams.
        '''</summary>
        Friend ReadOnly Property 保存参数() As String
            Get
                Return ResourceManager.GetString("保存参数", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SaveConfig.
        '''</summary>
        Friend ReadOnly Property 保存配置() As String
            Get
                Return ResourceManager.GetString("保存配置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend ReadOnly Property 停止() As String
            Get
                Return ResourceManager.GetString("停止", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 停止运动.
        '''</summary>
        Friend ReadOnly Property 停止运动() As String
            Get
                Return ResourceManager.GetString("停止运动", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow.
        '''</summary>
        Friend ReadOnly Property 允许() As String
            Get
                Return ResourceManager.GetString("允许", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 光栅异物移除.
        '''</summary>
        Friend ReadOnly Property 光栅异物移除() As String
            Get
                Return ResourceManager.GetString("光栅异物移除", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 光栅报警.
        '''</summary>
        Friend ReadOnly Property 光栅报警() As String
            Get
                Return ResourceManager.GetString("光栅报警", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 减速.
        '''</summary>
        Friend ReadOnly Property 减速() As String
            Get
                Return ResourceManager.GetString("减速", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 减速停.
        '''</summary>
        Friend ReadOnly Property 减速停() As String
            Get
                Return ResourceManager.GetString("减速停", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 减速停止.
        '''</summary>
        Friend ReadOnly Property 减速停止() As String
            Get
                Return ResourceManager.GetString("减速停止", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedDownTime：.
        '''</summary>
        Friend ReadOnly Property 减速时间() As String
            Get
                Return ResourceManager.GetString("减速时间", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedDownRatio：.
        '''</summary>
        Friend ReadOnly Property 减速比() As String
            Get
                Return ResourceManager.GetString("减速比", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedDownPulse：.
        '''</summary>
        Friend ReadOnly Property 减速脉冲() As String
            Get
                Return ResourceManager.GetString("减速脉冲", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 初始化失败.
        '''</summary>
        Friend ReadOnly Property 初始化失败() As String
            Get
                Return ResourceManager.GetString("初始化失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property 删除() As String
            Get
                Return ResourceManager.GetString("删除", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DeletePosition.
        '''</summary>
        Friend ReadOnly Property 删除位置() As String
            Get
                Return ResourceManager.GetString("删除位置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DeleteAxisName.
        '''</summary>
        Friend ReadOnly Property 删除轴名称() As String
            Get
                Return ResourceManager.GetString("删除轴名称", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DeleteSelectSpeed.
        '''</summary>
        Friend ReadOnly Property 删除选中速度() As String
            Get
                Return ResourceManager.GetString("删除选中速度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DeleteAxisConfig.
        '''</summary>
        Friend ReadOnly Property 删除配置结果() As String
            Get
                Return ResourceManager.GetString("删除配置结果", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arrived.
        '''</summary>
        Friend ReadOnly Property 到位() As String
            Get
                Return ResourceManager.GetString("到位", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 到位信号发送.
        '''</summary>
        Friend ReadOnly Property 到位信号发送() As String
            Get
                Return ResourceManager.GetString("到位信号发送", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedUpTime：.
        '''</summary>
        Friend ReadOnly Property 加速时间() As String
            Get
                Return ResourceManager.GetString("加速时间", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedUpPulse：.
        '''</summary>
        Friend ReadOnly Property 加速脉冲() As String
            Get
                Return ResourceManager.GetString("加速脉冲", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CardNo.
        '''</summary>
        Friend ReadOnly Property 卡号() As String
            Get
                Return ResourceManager.GetString("卡号", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ChooseCardNo.
        '''</summary>
        Friend ReadOnly Property 卡号选择() As String
            Get
                Return ResourceManager.GetString("卡号选择", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CardNo.
        '''</summary>
        Friend ReadOnly Property 卡数量() As String
            Get
                Return ResourceManager.GetString("卡数量", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CardType.
        '''</summary>
        Friend ReadOnly Property 卡类型() As String
            Get
                Return ResourceManager.GetString("卡类型", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HomeValidSignal.
        '''</summary>
        Friend ReadOnly Property 原点有效电平() As String
            Get
                Return ResourceManager.GetString("原点有效电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HomeFilterEnable.
        '''</summary>
        Friend ReadOnly Property 原点滤波使能() As String
            Get
                Return ResourceManager.GetString("原点滤波使能", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetHome.
        '''</summary>
        Friend ReadOnly Property 原点设置() As String
            Get
                Return ResourceManager.GetString("原点设置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 参数.
        '''</summary>
        Friend ReadOnly Property 参数() As String
            Get
                Return ResourceManager.GetString("参数", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ImportParams.
        '''</summary>
        Friend ReadOnly Property 参数导入() As String
            Get
                Return ResourceManager.GetString("参数导入", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 参数文件不正确.
        '''</summary>
        Friend ReadOnly Property 参数文件不正确() As String
            Get
                Return ResourceManager.GetString("参数文件不正确", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetParams.
        '''</summary>
        Friend ReadOnly Property 参数设置() As String
            Get
                Return ResourceManager.GetString("参数设置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RebellionDirection.
        '''</summary>
        Friend ReadOnly Property 反向() As String
            Get
                Return ResourceManager.GetString("反向", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property 取消() As String
            Get
                Return ResourceManager.GetString("取消", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 变速.
        '''</summary>
        Friend ReadOnly Property 变速() As String
            Get
                Return ResourceManager.GetString("变速", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UsableInput.
        '''</summary>
        Friend ReadOnly Property 可用输入() As String
            Get
                Return ResourceManager.GetString("可用输入", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UsableOutPut.
        '''</summary>
        Friend ReadOnly Property 可用输出() As String
            Get
                Return ResourceManager.GetString("可用输出", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property 名称() As String
            Get
                Return ResourceManager.GetString("名称", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 后台繁忙.
        '''</summary>
        Friend ReadOnly Property 后台繁忙() As String
            Get
                Return ResourceManager.GetString("后台繁忙", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StartSpeed：.
        '''</summary>
        Friend ReadOnly Property 启动速度() As String
            Get
                Return ResourceManager.GetString("启动速度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 回原点.
        '''</summary>
        Friend ReadOnly Property 回原点() As String
            Get
                Return ResourceManager.GetString("回原点", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackHomeEZCount.
        '''</summary>
        Friend ReadOnly Property 回原点EZ个数() As String
            Get
                Return ResourceManager.GetString("回原点EZ个数", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackHomeDirection.
        '''</summary>
        Friend ReadOnly Property 回原点方向() As String
            Get
                Return ResourceManager.GetString("回原点方向", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackHomeMode.
        '''</summary>
        Friend ReadOnly Property 回原点模式() As String
            Get
                Return ResourceManager.GetString("回原点模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackHomeSpeedMode.
        '''</summary>
        Friend ReadOnly Property 回原点速度模式() As String
            Get
                Return ResourceManager.GetString("回原点速度模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Friend ReadOnly Property 型号() As String
            Get
                Return ResourceManager.GetString("型号", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BackHome.
        '''</summary>
        Friend ReadOnly Property 复位() As String
            Get
                Return ResourceManager.GetString("复位", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReplaceSpeed：.
        '''</summary>
        Friend ReadOnly Property 复位速度() As String
            Get
                Return ResourceManager.GetString("复位速度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relationship.
        '''</summary>
        Friend ReadOnly Property 对应关系() As String
            Get
                Return ResourceManager.GetString("对应关系", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 开始.
        '''</summary>
        Friend ReadOnly Property 开始() As String
            Get
                Return ResourceManager.GetString("开始", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tense.
        '''</summary>
        Friend ReadOnly Property 张() As String
            Get
                Return ResourceManager.GetString("张", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 当前值.
        '''</summary>
        Friend ReadOnly Property 当前值() As String
            Get
                Return ResourceManager.GetString("当前值", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CurrentStatus.
        '''</summary>
        Friend ReadOnly Property 当前状态() As String
            Get
                Return ResourceManager.GetString("当前状态", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 急停报警.
        '''</summary>
        Friend ReadOnly Property 急停报警() As String
            Get
                Return ResourceManager.GetString("急停报警", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warn.
        '''</summary>
        Friend ReadOnly Property 报警() As String
            Get
                Return ResourceManager.GetString("报警", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 持续运动.
        '''</summary>
        Friend ReadOnly Property 持续运动() As String
            Get
                Return ResourceManager.GetString("持续运动", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指令发送失败.
        '''</summary>
        Friend ReadOnly Property 指令发送失败() As String
            Get
                Return ResourceManager.GetString("指令发送失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指令发送成功.
        '''</summary>
        Friend ReadOnly Property 指令发送成功() As String
            Get
                Return ResourceManager.GetString("指令发送成功", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ChangeSelectSpeed.
        '''</summary>
        Friend ReadOnly Property 改变选中速度() As String
            Get
                Return ResourceManager.GetString("改变选中速度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid.
        '''</summary>
        Friend ReadOnly Property 无效() As String
            Get
                Return ResourceManager.GetString("无效", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 无需添加.
        '''</summary>
        Friend ReadOnly Property 无需添加() As String
            Get
                Return ResourceManager.GetString("无需添加", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 暂停.
        '''</summary>
        Friend ReadOnly Property 暂停() As String
            Get
                Return ResourceManager.GetString("暂停", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MaxSpeed：.
        '''</summary>
        Friend ReadOnly Property 最大速度() As String
            Get
                Return ResourceManager.GetString("最大速度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valid.
        '''</summary>
        Friend ReadOnly Property 有效() As String
            Get
                Return ResourceManager.GetString("有效", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未找到轴配置文件.
        '''</summary>
        Friend ReadOnly Property 未找到轴配置文件() As String
            Get
                Return ResourceManager.GetString("未找到轴配置文件", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StraightDirection.
        '''</summary>
        Friend ReadOnly Property 正向() As String
            Get
                Return ResourceManager.GetString("正向", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Front.
        '''</summary>
        Friend ReadOnly Property 正方向() As String
            Get
                Return ResourceManager.GetString("正方向", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RightLimited.
        '''</summary>
        Friend ReadOnly Property 正极限() As String
            Get
                Return ResourceManager.GetString("正极限", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RightLimitedWarn.
        '''</summary>
        Friend ReadOnly Property 正极限报警() As String
            Get
                Return ResourceManager.GetString("正极限报警", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 此位置已经有.
        '''</summary>
        Friend ReadOnly Property 此位置已经有() As String
            Get
                Return ResourceManager.GetString("此位置已经有", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test.
        '''</summary>
        Friend ReadOnly Property 测试() As String
            Get
                Return ResourceManager.GetString("测试", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property 添加() As String
            Get
                Return ResourceManager.GetString("添加", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADDPosition.
        '''</summary>
        Friend ReadOnly Property 添加位置() As String
            Get
                Return ResourceManager.GetString("添加位置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddCard.
        '''</summary>
        Friend ReadOnly Property 添加卡() As String
            Get
                Return ResourceManager.GetString("添加卡", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddInput.
        '''</summary>
        Friend ReadOnly Property 添加输入() As String
            Get
                Return ResourceManager.GetString("添加输入", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddOutPut.
        '''</summary>
        Friend ReadOnly Property 添加输出() As String
            Get
                Return ResourceManager.GetString("添加输出", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddSpeed.
        '''</summary>
        Friend ReadOnly Property 添加速度() As String
            Get
                Return ResourceManager.GetString("添加速度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddProject.
        '''</summary>
        Friend ReadOnly Property 添加项目() As String
            Get
                Return ResourceManager.GetString("添加项目", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddProjectName.
        '''</summary>
        Friend ReadOnly Property 添加项目名称() As String
            Get
                Return ResourceManager.GetString("添加项目名称", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddProjectStatusA.
        '''</summary>
        Friend ReadOnly Property 添加项目状态A() As String
            Get
                Return ResourceManager.GetString("添加项目状态A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AddProjectStatusB.
        '''</summary>
        Friend ReadOnly Property 添加项目状态B() As String
            Get
                Return ResourceManager.GetString("添加项目状态B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PointRunMode.
        '''</summary>
        Friend ReadOnly Property 点动移动模式() As String
            Get
                Return ResourceManager.GetString("点动移动模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend ReadOnly Property 状态() As String
            Get
                Return ResourceManager.GetString("状态", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 目标位置：.
        '''</summary>
        Friend ReadOnly Property 目标位置() As String
            Get
                Return ResourceManager.GetString("目标位置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AlwaysRunMode.
        '''</summary>
        Friend ReadOnly Property 直运模式() As String
            Get
                Return ResourceManager.GetString("直运模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 相对运动.
        '''</summary>
        Friend ReadOnly Property 相对运动() As String
            Get
                Return ResourceManager.GetString("相对运动", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RelativeRunMode.
        '''</summary>
        Friend ReadOnly Property 相对运动模式() As String
            Get
                Return ResourceManager.GetString("相对运动模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ensure.
        '''</summary>
        Friend ReadOnly Property 确定() As String
            Get
                Return ResourceManager.GetString("确定", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 碰到光栅.
        '''</summary>
        Friend ReadOnly Property 碰到光栅() As String
            Get
                Return ResourceManager.GetString("碰到光栅", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Foebid.
        '''</summary>
        Friend ReadOnly Property 禁止() As String
            Get
                Return ResourceManager.GetString("禁止", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LeaveHomeDirection.
        '''</summary>
        Friend ReadOnly Property 离开原点方向() As String
            Get
                Return ResourceManager.GetString("离开原点方向", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MOVE.
        '''</summary>
        Friend ReadOnly Property 移动() As String
            Get
                Return ResourceManager.GetString("移动", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PromptlyStop.
        '''</summary>
        Friend ReadOnly Property 立即停止() As String
            Get
                Return ResourceManager.GetString("立即停止", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 等待用户指令.
        '''</summary>
        Friend ReadOnly Property 等待用户指令() As String
            Get
                Return ResourceManager.GetString("等待用户指令", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property 类型() As String
            Get
                Return ResourceManager.GetString("类型", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ChooseType.
        '''</summary>
        Friend ReadOnly Property 类型选择() As String
            Get
                Return ResourceManager.GetString("类型选择", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 给出状态格式不正确.
        '''</summary>
        Friend ReadOnly Property 给出状态格式不正确() As String
            Get
                Return ResourceManager.GetString("给出状态格式不正确", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 绝对运动.
        '''</summary>
        Friend ReadOnly Property 绝对运动() As String
            Get
                Return ResourceManager.GetString("绝对运动", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CodeCountMode.
        '''</summary>
        Friend ReadOnly Property 编码计数模式() As String
            Get
                Return ResourceManager.GetString("编码计数模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pulse.
        '''</summary>
        Friend ReadOnly Property 脉冲() As String
            Get
                Return ResourceManager.GetString("脉冲", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PulseMode.
        '''</summary>
        Friend ReadOnly Property 脉冲模式() As String
            Get
                Return ResourceManager.GetString("脉冲模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请检查位置名.
        '''</summary>
        Friend ReadOnly Property 请检查位置名() As String
            Get
                Return ResourceManager.GetString("请检查位置名", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请检查文件是否缺失.
        '''</summary>
        Friend ReadOnly Property 请检查文件是否缺失() As String
            Get
                Return ResourceManager.GetString("请检查文件是否缺失", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请输入要添加的位置.
        '''</summary>
        Friend ReadOnly Property 请输入要添加的位置() As String
            Get
                Return ResourceManager.GetString("请输入要添加的位置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReadParams.
        '''</summary>
        Friend ReadOnly Property 读取参数() As String
            Get
                Return ResourceManager.GetString("读取参数", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 读取当前脉冲.
        '''</summary>
        Friend ReadOnly Property 读取当前脉冲() As String
            Get
                Return ResourceManager.GetString("读取当前脉冲", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 负向.
        '''</summary>
        Friend ReadOnly Property 负向() As String
            Get
                Return ResourceManager.GetString("负向", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back.
        '''</summary>
        Friend ReadOnly Property 负方向() As String
            Get
                Return ResourceManager.GetString("负方向", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LeftLImited.
        '''</summary>
        Friend ReadOnly Property 负极限() As String
            Get
                Return ResourceManager.GetString("负极限", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LeftLImitedWarn.
        '''</summary>
        Friend ReadOnly Property 负极限报警() As String
            Get
                Return ResourceManager.GetString("负极限报警", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 超时报警.
        '''</summary>
        Friend ReadOnly Property 超时报警() As String
            Get
                Return ResourceManager.GetString("超时报警", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SoftWareLimitEnable.
        '''</summary>
        Friend ReadOnly Property 软件极限使能() As String
            Get
                Return ResourceManager.GetString("软件极限使能", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Axis.
        '''</summary>
        Friend ReadOnly Property 轴() As String
            Get
                Return ResourceManager.GetString("轴", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AxisInitialise.
        '''</summary>
        Friend ReadOnly Property 轴初始化失败() As String
            Get
                Return ResourceManager.GetString("轴初始化失败", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AxisNo.
        '''</summary>
        Friend ReadOnly Property 轴号() As String
            Get
                Return ResourceManager.GetString("轴号", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AxisName.
        '''</summary>
        Friend ReadOnly Property 轴名称() As String
            Get
                Return ResourceManager.GetString("轴名称", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InputOperate.
        '''</summary>
        Friend ReadOnly Property 输入操作() As String
            Get
                Return ResourceManager.GetString("输入操作", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OutputOperate.
        '''</summary>
        Friend ReadOnly Property 输出操作() As String
            Get
                Return ResourceManager.GetString("输出操作", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OutputType.
        '''</summary>
        Friend ReadOnly Property 输出类型() As String
            Get
                Return ResourceManager.GetString("输出类型", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run.
        '''</summary>
        Friend ReadOnly Property 运动() As String
            Get
                Return ResourceManager.GetString("运动", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 运动到位.
        '''</summary>
        Friend ReadOnly Property 运动到位() As String
            Get
                Return ResourceManager.GetString("运动到位", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 运动异常.
        '''</summary>
        Friend ReadOnly Property 运动异常() As String
            Get
                Return ResourceManager.GetString("运动异常", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RunTimeOut.
        '''</summary>
        Friend ReadOnly Property 运动超时() As String
            Get
                Return ResourceManager.GetString("运动超时", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 运动距离.
        '''</summary>
        Friend ReadOnly Property 运动距离() As String
            Get
                Return ResourceManager.GetString("运动距离", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ChooseAxis.
        '''</summary>
        Friend ReadOnly Property 运动轴选择() As String
            Get
                Return ResourceManager.GetString("运动轴选择", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quit.
        '''</summary>
        Friend ReadOnly Property 退出() As String
            Get
                Return ResourceManager.GetString("退出", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 速度.
        '''</summary>
        Friend ReadOnly Property 速度() As String
            Get
                Return ResourceManager.GetString("速度", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedName：.
        '''</summary>
        Friend ReadOnly Property 速度名称() As String
            Get
                Return ResourceManager.GetString("速度名称", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedBightMode.
        '''</summary>
        Friend ReadOnly Property 速度曲线模式() As String
            Get
                Return ResourceManager.GetString("速度曲线模式", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedType.
        '''</summary>
        Friend ReadOnly Property 速度类型() As String
            Get
                Return ResourceManager.GetString("速度类型", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EditSpeed.
        '''</summary>
        Friend ReadOnly Property 速度编辑() As String
            Get
                Return ResourceManager.GetString("速度编辑", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpeedSetup.
        '''</summary>
        Friend ReadOnly Property 速度设置() As String
            Get
                Return ResourceManager.GetString("速度设置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ChooseSpeed.
        '''</summary>
        Friend ReadOnly Property 速度选择() As String
            Get
                Return ResourceManager.GetString("速度选择", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NotAB.
        '''</summary>
        Friend ReadOnly Property 非AB() As String
            Get
                Return ResourceManager.GetString("非AB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 马上停.
        '''</summary>
        Friend ReadOnly Property 马上停() As String
            Get
                Return ResourceManager.GetString("马上停", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetDriveParams.
        '''</summary>
        Friend ReadOnly Property 驱动参数设置() As String
            Get
                Return ResourceManager.GetString("驱动参数设置", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HightSignal.
        '''</summary>
        Friend ReadOnly Property 高电平() As String
            Get
                Return ResourceManager.GetString("高电平", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HightSpeed.
        '''</summary>
        Friend ReadOnly Property 高速() As String
            Get
                Return ResourceManager.GetString("高速", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
